[DatabaseConfig]
name = "users"    # name of a database
port = "3307"     # port for connection 
username = "root" # username for logging credentials
password = "test" # password for logging credentials
