[DatabaseConfig]
name = ""     # name of a database
port = ""     # port for connection 
username = "" # username for logging credentials
password = "" # password for logging credentials
[RouterConfig]
# WARNING: no v1, v2, etc.
base_url = "/api/" # base url for router incoming connections
